[providers]
node = {}

[ phases.build ]
cmds = [ "npm install", "npm run build" ]

[ phases.setup ]
cmds = [ "npm install" ]

[ phases.start ]
cmds = [ "node server.js" ]

[variables]
NODE_ENV = "production"
