providers = ["node"]

[ phases.setup ]
cmds = [ "npm install --ignore-scripts" ]

[ phases.build ]
cmds = [ "npm rebuild better-sqlite3 --build-from-source", "node db/migrate.js" ]

[ phases.start ]
cmds = [ "node server.js" ]

[variables]
NODE_ENV = "production"
